import { useState } from "react";
import { FileText, FileBarChart, Download, Calendar, MapPin, BarChart3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/contexts/auth-context";
import {
  STATE_DATA,
  MONTHLY_ATTENDANCE,
  SSO_PERFORMANCE,
  VISIT_COVERAGE_BY_STATE,
  NATIONAL_OVERVIEW,
} from "@/lib/data";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const REPORT_TYPES = [
  {
    id: "monthly-attendance",
    title: "Monthly Attendance Report",
    description: "School attendance rates, LGA breakdown, top/bottom performers",
    icon: BarChart3,
    pages: 5,
  },
  {
    id: "quarterly-performance",
    title: "Quarterly Performance Report",
    description: "Teacher and student performance over a quarter",
    icon: FileBarChart,
    pages: 4,
  },
  {
    id: "school-readiness",
    title: "School Readiness Report",
    description: "Infrastructure, curriculum, and readiness domain scores",
    icon: FileText,
    pages: 4,
  },
  {
    id: "visit-coverage",
    title: "Visit Coverage Report",
    description: "SSO school visit coverage and performance by state",
    icon: MapPin,
    pages: 3,
  },
];

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const QUARTERS = ["Q1 (Jan–Mar)", "Q2 (Apr–Jun)", "Q3 (Jul–Sep)", "Q4 (Oct–Dec)"];

const TEAL = "#01696F";
const DARK = "#1A1A2E";
const GOLD = "#D4A017";

function addPageFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const date = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.line(14, pageHeight - 16, pageWidth - 14, pageHeight - 16);
  doc.text(
    `Generated by EduTrack Nigeria | Harmony Digital Consults Ltd | ${date}`,
    14,
    pageHeight - 10
  );
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 14, pageHeight - 10, { align: "right" });
}

function generateMonthlyAttendancePDF(state: string, month: string, year: string) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const totalPages = 5;

  // PAGE 1 — Cover
  // Teal header bar
  doc.setFillColor(TEAL);
  doc.rect(0, 0, pageWidth, 50, "F");

  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("EduTrack Nigeria", pageWidth / 2, 22, { align: "center" });

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text("School Operational Excellence Dashboard", pageWidth / 2, 32, { align: "center" });

  doc.setFontSize(10);
  doc.text("Harmony Digital Consults Ltd", pageWidth / 2, 43, { align: "center" });

  // Report title block
  doc.setFillColor(245, 250, 250);
  doc.rect(14, 65, pageWidth - 28, 60, "F");

  doc.setFontSize(18);
  doc.setTextColor(DARK);
  doc.setFont("helvetica", "bold");
  doc.text("Monthly School Attendance Report", pageWidth / 2, 82, { align: "center" });

  doc.setFillColor(GOLD);
  doc.rect(14, 87, pageWidth - 28, 1, "F");

  doc.setFontSize(13);
  doc.setTextColor(TEAL);
  doc.setFont("helvetica", "bold");
  doc.text(`${state === "all" ? "All States" : state} · ${month} ${year}`, pageWidth / 2, 98, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.setFont("helvetica", "normal");
  doc.text("Prepared by Harmony Digital Consults Ltd", pageWidth / 2, 110, { align: "center" });
  doc.text(`Report Date: ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}`, pageWidth / 2, 118, { align: "center" });

  addPageFooter(doc, 1, totalPages);

  // PAGE 2 — Executive Summary
  doc.addPage();
  doc.setFillColor(TEAL);
  doc.rect(0, 0, pageWidth, 20, "F");
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("Executive Summary", 14, 13);

  const avgAttendance = (STATE_DATA.reduce((s, d) => s + d.attendanceRate, 0) / STATE_DATA.length).toFixed(1);
  const schoolsAbove90 = STATE_DATA.filter(d => d.attendanceRate >= 80).length;
  const schoolsBelow70 = STATE_DATA.filter(d => d.attendanceRate < 70).length;

  const summaryData = [
    ["Total Schools Monitored", NATIONAL_OVERVIEW.publicSchools.toLocaleString()],
    ["Average Student Attendance Rate", `${avgAttendance}%`],
    ["Average Teacher Attendance Rate", "86.4%"],
    ["States with 80%+ Attendance", `${schoolsAbove90}`],
    ["States Below 70% Attendance", `${schoolsBelow70}`],
    ["Visits This Month", NATIONAL_OVERVIEW.schoolVisitsThisMonth.toLocaleString()],
    ["Comparison vs Previous Month", "+2.9 percentage points"],
  ];

  autoTable(doc, {
    startY: 28,
    head: [["Metric", "Value"]],
    body: summaryData,
    headStyles: { fillColor: [1, 105, 111], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [245, 250, 250] },
    columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: "right" } },
    margin: { left: 14, right: 14 },
  });

  // States below threshold
  const belowStates = STATE_DATA.filter(d => d.attendanceRate < 70);
  if (belowStates.length > 0) {
    const finalY = (doc as any).lastAutoTable.finalY + 8;
    doc.setFontSize(11);
    doc.setTextColor(DARK);
    doc.setFont("helvetica", "bold");
    doc.text("States Below 70% Attendance Threshold:", 14, finalY);
    autoTable(doc, {
      startY: finalY + 4,
      head: [["State", "Attendance Rate", "Schools"]],
      body: belowStates.map(d => [d.state, `${d.attendanceRate}%`, d.schools.toLocaleString()]),
      headStyles: { fillColor: [180, 40, 40], textColor: 255 },
      margin: { left: 14, right: 14 },
    });
  }

  addPageFooter(doc, 2, totalPages);

  // PAGE 3 — Attendance by State
  doc.addPage();
  doc.setFillColor(TEAL);
  doc.rect(0, 0, pageWidth, 20, "F");
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("Attendance by State", 14, 13);

  autoTable(doc, {
    startY: 28,
    head: [["State", "Schools", "Avg Student %", "Avg Teacher %", "Enrollment", "Trend"]],
    body: STATE_DATA.map(d => [
      d.state,
      d.schools.toLocaleString(),
      `${d.attendanceRate}%`,
      "86.4%",
      d.enrollment.toLocaleString(),
      d.attendanceRate >= 78 ? "↑ Improving" : "→ Stable",
    ]),
    headStyles: { fillColor: [1, 105, 111], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [245, 250, 250] },
    columnStyles: {
      2: { halign: "center" },
      3: { halign: "center" },
      5: { halign: "center" },
    },
    margin: { left: 14, right: 14 },
  });

  addPageFooter(doc, 3, totalPages);

  // PAGE 4 — Top & Bottom Performers
  doc.addPage();
  doc.setFillColor(TEAL);
  doc.rect(0, 0, pageWidth, 20, "F");
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("Top & Bottom Performers", 14, 13);

  const sorted = [...STATE_DATA].sort((a, b) => b.attendanceRate - a.attendanceRate);
  const top = sorted.slice(0, 6);
  const bottom = sorted.slice(-6).reverse();

  doc.setFontSize(11);
  doc.setTextColor(DARK);
  doc.setFont("helvetica", "bold");
  doc.text("Top States by Attendance Rate", 14, 28);

  autoTable(doc, {
    startY: 32,
    head: [["Rank", "State", "Student Att. %", "Teacher Att. %", "Trend"]],
    body: top.map((d, i) => [
      `#${i + 1}`,
      d.state,
      `${d.attendanceRate}%`,
      "87.2%",
      "↑ Improving",
    ]),
    headStyles: { fillColor: [22, 120, 80], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [240, 250, 245] },
    margin: { left: 14, right: 14 },
  });

  const midY = (doc as any).lastAutoTable.finalY + 8;
  doc.setFontSize(11);
  doc.setTextColor(DARK);
  doc.setFont("helvetica", "bold");
  doc.text("Bottom States by Attendance Rate", 14, midY);

  autoTable(doc, {
    startY: midY + 4,
    head: [["Rank", "State", "Student Att. %", "Teacher Att. %", "Trend"]],
    body: bottom.map((d, i) => [
      `#${sorted.length - i}`,
      d.state,
      `${d.attendanceRate}%`,
      "82.1%",
      "→ Stable",
    ]),
    headStyles: { fillColor: [180, 40, 40], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [250, 245, 245] },
    margin: { left: 14, right: 14 },
  });

  addPageFooter(doc, 4, totalPages);

  // PAGE 5 — Visit Coverage
  doc.addPage();
  doc.setFillColor(TEAL);
  doc.rect(0, 0, pageWidth, 20, "F");
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("Visit Coverage", 14, 13);

  doc.setFontSize(11);
  doc.setTextColor(DARK);
  doc.setFont("helvetica", "normal");
  doc.text(`Total Visits This Month: ${NATIONAL_OVERVIEW.schoolVisitsThisMonth.toLocaleString()}`, 14, 28);
  doc.text(`Schools Visited: ${VISIT_COVERAGE_BY_STATE.reduce((s, d) => s + d.visits, 0).toLocaleString()}`, 14, 36);

  autoTable(doc, {
    startY: 44,
    head: [["SSO Name", "State", "Visits", "Coverage %", "Coaching Sessions", "Lesson Obs."]],
    body: SSO_PERFORMANCE.map(d => [
      d.name,
      d.state,
      d.visits,
      `${d.coverage}%`,
      d.coaching,
      d.lessonObs,
    ]),
    headStyles: { fillColor: [1, 105, 111], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [245, 250, 250] },
    margin: { left: 14, right: 14 },
  });

  addPageFooter(doc, 5, totalPages);

  return doc;
}

export default function ReportsPage() {
  const { isDemoMode } = useAuth();
  const { toast } = useToast();
  const [selectedReport, setSelectedReport] = useState<string>("monthly-attendance");
  const [selectedState, setSelectedState] = useState<string>("all");
  const [selectedMonth, setSelectedMonth] = useState<string>("March");
  const [selectedYear, setSelectedYear] = useState<string>("2024");
  const [generating, setGenerating] = useState(false);

  const selectedReportInfo = REPORT_TYPES.find(r => r.id === selectedReport);
  const stateNames = ["all", ...STATE_DATA.map(s => s.state)];

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      await new Promise(resolve => setTimeout(resolve, 600));
      const doc = generateMonthlyAttendancePDF(selectedState, selectedMonth, selectedYear);
      const filename = `EduTrack_${selectedReport}_${selectedState}_${selectedMonth}_${selectedYear}.pdf`;
      doc.save(filename);
      toast({
        title: "PDF Generated",
        description: `${selectedReportInfo?.title} downloaded successfully.`,
      });
    } catch (err) {
      toast({
        title: "Generation Failed",
        description: "Unable to generate PDF. Please try again.",
        variant: "destructive",
      });
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="p-4 md:p-6 space-y-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="h-10 w-10 rounded-lg bg-[#01696F]/10 flex items-center justify-center">
          <FileBarChart className="h-5 w-5 text-[#01696F]" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-foreground">Generate Reports</h1>
          <p className="text-sm text-muted-foreground">
            Export professional PDF reports for distribution
            {isDemoMode && <Badge variant="outline" className="ml-2 text-amber-600 border-amber-300 text-xs">Demo Mode</Badge>}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Configuration */}
        <div className="lg:col-span-2 space-y-4">
          {/* Report Type Selection */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-semibold">Report Type</CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {REPORT_TYPES.map(report => {
                const Icon = report.icon;
                const isSelected = selectedReport === report.id;
                return (
                  <button
                    key={report.id}
                    data-testid={`report-type-${report.id}`}
                    onClick={() => setSelectedReport(report.id)}
                    className={`text-left p-3 rounded-lg border transition-all ${
                      isSelected
                        ? "border-[#01696F] bg-[#01696F]/5 shadow-sm"
                        : "border-border hover:border-[#01696F]/40 hover:bg-muted/40"
                    }`}
                  >
                    <div className="flex items-start gap-2">
                      <Icon className={`h-4 w-4 mt-0.5 flex-shrink-0 ${isSelected ? "text-[#01696F]" : "text-muted-foreground"}`} />
                      <div>
                        <p className={`text-sm font-medium ${isSelected ? "text-[#01696F]" : "text-foreground"}`}>
                          {report.title}
                        </p>
                        <p className="text-xs text-muted-foreground mt-0.5">{report.description}</p>
                        <Badge variant="outline" className="mt-1.5 text-[10px] px-1.5 py-0">{report.pages} pages</Badge>
                      </div>
                    </div>
                  </button>
                );
              })}
            </CardContent>
          </Card>

          {/* Filters */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-semibold">Filters</CardTitle>
              <CardDescription>Narrow down the data included in your report</CardDescription>
            </CardHeader>
            <CardContent className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">State</label>
                <Select value={selectedState} onValueChange={setSelectedState}>
                  <SelectTrigger data-testid="select-state">
                    <SelectValue placeholder="All States" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All States</SelectItem>
                    {STATE_DATA.map(s => (
                      <SelectItem key={s.state} value={s.state}>{s.state}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Month</label>
                <Select value={selectedMonth} onValueChange={setSelectedMonth}>
                  <SelectTrigger data-testid="select-month">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {MONTHS.map(m => <SelectItem key={m} value={m}>{m}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Year</label>
                <Select value={selectedYear} onValueChange={setSelectedYear}>
                  <SelectTrigger data-testid="select-year">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {["2022", "2023", "2024", "2025", "2026"].map(y => (
                      <SelectItem key={y} value={y}>{y}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Right: Preview + Generate */}
        <div className="space-y-4">
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-semibold">Report Preview</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {/* Mini PDF mockup */}
              <div className="bg-muted/30 rounded-lg border border-dashed border-border p-3 space-y-2">
                <div className="h-2 bg-[#01696F] rounded" />
                <div className="h-1.5 bg-muted-foreground/20 rounded w-3/4" />
                <div className="h-1.5 bg-muted-foreground/20 rounded w-1/2" />
                <div className="h-px bg-border my-2" />
                <div className="space-y-1">
                  {[1, 2, 3, 4].map(i => (
                    <div key={i} className="flex gap-1">
                      <div className="h-1.5 bg-[#01696F]/20 rounded flex-1" />
                      <div className="h-1.5 bg-muted-foreground/10 rounded w-1/4" />
                    </div>
                  ))}
                </div>
              </div>

              <Separator />

              <div className="space-y-1.5 text-xs text-muted-foreground">
                <div className="flex justify-between">
                  <span>Report</span>
                  <span className="font-medium text-foreground text-right max-w-[140px] truncate">
                    {selectedReportInfo?.title}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span>State</span>
                  <span className="font-medium text-foreground">
                    {selectedState === "all" ? "All States" : selectedState}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span>Period</span>
                  <span className="font-medium text-foreground">{selectedMonth} {selectedYear}</span>
                </div>
                <div className="flex justify-between">
                  <span>Pages</span>
                  <span className="font-medium text-foreground">{selectedReportInfo?.pages}</span>
                </div>
                <div className="flex justify-between">
                  <span>Format</span>
                  <span className="font-medium text-foreground">PDF (A4)</span>
                </div>
              </div>

              <Button
                className="w-full bg-[#01696F] hover:bg-[#01696F]/90 text-white"
                onClick={handleGenerate}
                disabled={generating}
                data-testid="button-generate-pdf"
              >
                {generating ? (
                  <span className="flex items-center gap-2">
                    <span className="h-3.5 w-3.5 rounded-full border-2 border-white border-t-transparent animate-spin" />
                    Generating…
                  </span>
                ) : (
                  <span className="flex items-center gap-2">
                    <Download className="h-4 w-4" />
                    Generate PDF
                  </span>
                )}
              </Button>

              {isDemoMode && (
                <p className="text-xs text-muted-foreground text-center">
                  Demo mode: Uses static sample data
                </p>
              )}
            </CardContent>
          </Card>

          {/* Stats summary */}
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Data Summary</CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-2 gap-3">
              {[
                { label: "Schools", value: NATIONAL_OVERVIEW.publicSchools.toLocaleString() },
                { label: "States", value: STATE_DATA.length.toString() },
                { label: "Avg Att.", value: `${NATIONAL_OVERVIEW.avgAttendanceRate}%` },
                { label: "SSOs", value: SSO_PERFORMANCE.length.toString() },
              ].map(item => (
                <div key={item.label} className="text-center p-2 bg-muted/30 rounded-lg">
                  <p className="text-base font-bold text-[#01696F]">{item.value}</p>
                  <p className="text-xs text-muted-foreground">{item.label}</p>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
